server:
  port: 8080
  servlet:
    context-path:
    jsp:
      registered: false
  error:
    whitelabel:
      enabled: false

spring:
  profiles-active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/rncp?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: Pierrebing59
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
##logging:
  ##config: classpath:logback-spring-dev-xml